# Created by Abhay Kumar(uiv14167)
# Version 1.0
# Last Updated: 23/07/2024
# Last Updated: 28/10/2024
# FF Framed Added Column for Voltage Diveder Ratio
-- -----------------------------------------------------
-- Drop Schema ltt_result_input_tables if already exists and create new 
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS LTT_RESULT_INPUT_TABLES ;

CREATE SCHEMA IF NOT EXISTS LTT_RESULT_INPUT_TABLES ;

-- -----------------------------------------------------
-- Use  `ltt_result_input_tables`
-- -----------------------------------------------------

#USE LTT_RESULT_INPUT_TABLES ;

-- -----------------------------------------------------
-- Table `ltt_result_input_tables`.`poduct_test_names`
-- -----------------------------------------------------
CREATE TABLE LTT_RESULT_INPUT_TABLES.PRODUCT_TEST_NAMES
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
    PRODUCT_NAME            VARCHAR (255) NOT NULL COMMENT 'Product Name i.e. eDCU_48V, eDCU_96V --> Hardcoded and should have import export option from GUI',
    TEST_NAME               VARCHAR (255) NOT NULL COMMENT 'Test Name like VIBRATION TEST, THERMAL ENDURANCE TEST -> Hardcoded and should have import export option from GUI',
    MISSION_PROFILE         VARCHAR (255) COMMENT 'Test Name like MISSION PROFILE 1, MISSION PROFILE 2 SHORT -> Hardcoded and should have import export option from GUI',
    CYCLE_DURATION	        INT COMMENT 'Test Duration of one cycle in seconds -> Hardcoded and should have import export option from GUI',
	NUMBER_OF_CYCLES        INT COMMENT 'Number of Test cycle needed to run -> Hardcoded and should have import export option from GUI',
    TOTAL_DURATION          INT	COMMENT 'Total Test Duration of one cycle in seconds -> Hardcoded and should have import export option from GUI'
) COMMENT 'This table will contain the Test related information for the products';

-- -----------------------------------------------------
-- Creating indexes in the PRODUCT_TEST_NAMES table to optimise the query time
-- -----------------------------------------------------
CREATE INDEX TEST_NAME_INDEX ON LTT_RESULT_INPUT_TABLES.PRODUCT_TEST_NAMES (TEST_NAME);
CREATE INDEX PRODUCT_NAME_INDEX ON LTT_RESULT_INPUT_TABLES.PRODUCT_TEST_NAMES (PRODUCT_NAME);

-- -----------------------------------------------------
-- Insert data in PRODUCT_TEST_NAMES table based on mission Profile`
-- -----------------------------------------------------
INSERT INTO LTT_RESULT_INPUT_TABLES.PRODUCT_TEST_NAMES (PRODUCT_NAME,TEST_NAME,MISSION_PROFILE,CYCLE_DURATION,NUMBER_OF_CYCLES,TOTAL_DURATION) VALUES 
('eDCU','THERMAL ENDURANCE TEST','MISSION PROFILE 1', 4440, 1290, 5727600),
('eDCU','HIGH TEMPERATURE LIFE TEST','MISSION PROFILE 2 LONG', 611, 4800, 2932800),
('eDCU','VIBRATION TEST','MISSION PROFILE 2 SHORT', 611, 236, 144196)
;

-- -----------------------------------------------------
-- Table `ltt_result_input_tables`.`fa_frame_details` Which is containing the Software Version informations
-- -----------------------------------------------------
CREATE TABLE LTT_RESULT_INPUT_TABLES.FA_FRAME_DETAILS
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
    SIGNAL_NAME          	VARCHAR (255) COMMENT 'Name of Signal in FE Frame  --> Hardcoded and should have import export option from GUI',
    OFFSET_NUM				INT COMMENT 'Start Byte of the Signal in Return Data --> Hardcoded and should have import export option from GUI',
    NB_BYTES				INT	COMMENT 'Number of Bytes for the Signal in Return Data --> Hardcoded and should have import export option from GUI',
    MASK_Hex				VARCHAR (255) COMMENT 'Mask need for the Signal like 0x01, 0x0F  --> Hardcoded and should have import export option from GUI'
    
) COMMENT 'This table will store the details of FA Frames';
-- -----------------------------------------------------
-- Table `ltt_result_input_tables`.`fe_frame_details`
-- -----------------------------------------------------
CREATE TABLE LTT_RESULT_INPUT_TABLES.FE_FRAME_DETAILS
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
    SIGNAL_NAME             VARCHAR (255) COMMENT 'Name of Signal in FE Frame  --> Hardcoded and should have import export option from GUI',
    OFFSET_NUM				INT COMMENT 'Start Byte of the Signal in Return Data --> Hardcoded and should have import export option from GUI',
    NB_BYTES				INT	COMMENT 'Number of Bytes for the Signal in Return Data --> Hardcoded and should have import export option from GUI',
    MASK_Hex 				VARCHAR (255) COMMENT 'Mask need for the Signal like 0x01, 0x0F  --> Hardcoded and should have import export option from GUI',
    SCALING_FACTOR		    FLOAT(6) COMMENT 'Conversion formula for the Signal ex. M in  Mx+C, optional --> Hardcoded and should have import export option from GUI',
    SCALING_OFFSET		    FLOAT(6) COMMENT 'Conversion formula for the Signal ex. C in  Mx+C, optional --> Hardcoded and should have import export option from GUI',
    UNIT					VARCHAR (255) COMMENT 'Unit of the Signal --> GUI - Non-editable combo box',
    VOLTAGE_DIVIDER_RATIO	FLOAT(6) COMMENT 'Conversion formula for the Signal ex. C in  Mx+C, optional --> Hardcoded and should have import export option from GUI',
    DEFAULT_VALUE			INT	COMMENT 'DEFAULT_VALUE of the Signal --> Hardcoded and should have import export option from GUI',
    DISPLAY_TYPE			VARCHAR (255) COMMENT 'DISPLAY_TYPE of the Signal --> Hardcoded and should have import export option from GUI'
) COMMENT 'This table will store the details of FE Frames';

-- -----------------------------------------------------
-- Table `ltt_result_input_tables`.`ff_frame_details`
-- -----------------------------------------------------
CREATE TABLE LTT_RESULT_INPUT_TABLES.FF_FRAME_DETAILS
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
    SIGNAL_NAME          	VARCHAR (255) COMMENT 'Name of Signal in FE Frame  --> Hardcoded and should have import export option from GUI',
    OFFSET_NUM				INT COMMENT 'Start Byte of the Signal in Return Data --> Hardcoded and should have import export option from GUI',
    NB_BYTES				INT	COMMENT 'Number of Bytes for the Signal in Return Data --> Hardcoded and should have import export option from GUI',
    MASK_Hex				VARCHAR (255) COMMENT 'Mask need for the Signal like 0x01, 0x0F  --> Hardcoded and should have import export option from GUI',
    SCALING_FACTOR		    FLOAT(6)  COMMENT 'Conversion formula for the Signal ex. M in  Mx+C, optional --> Hardcoded and should have import export option from GUI',
    SCALING_OFFSET		    FLOAT(6)  COMMENT 'Conversion formula for the Signal ex. C in  Mx+C, optional --> Hardcoded and should have import export option from GUI',
    UNIT					VARCHAR (255) COMMENT 'Unit of the Signal -->  Hardcoded and should have import export option from GUI',
    VOLTAGE_DIVIDER_RATIO	FLOAT(6) COMMENT 'Conversion formula for the Signal ex. C in  Mx+C, optional --> Hardcoded and should have import export option from GUI',
    DEFAULT_VALUE			INT	COMMENT 'DEFAULT_VALUE of the Signal --> Hardcoded and should have import export option from GUI',
    DISPLAY_TYPE			VARCHAR (255) COMMENT 'DISPLAY_TYPE of the Signal --> Hardcoded and should have import export option from GUI'
    
) COMMENT 'This table will store the details of FF Frames';

-- -----------------------------------------------------
-- Table `ltt_result_input_tables`.`limit_table`
-- -----------------------------------------------------
CREATE TABLE LTT_RESULT_INPUT_TABLES.LIMIT_TABLE
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
    SIGNAL_NAME          	VARCHAR (255) NOT NULL COMMENT 'Name of Signal for which this limit is applicable  --> Hardcoded and should have import export option from GUI',
    COMPARISON_TYPE         VARCHAR (255) COMMENT 'Type of comparison like EQ(==) OR EQT(== +/-) OR GELE(>= <=) OR NE (!=)--> Hardcoded and should have import export option from GUI',
    ERROR_MESSSAGE          VARCHAR (255) COMMENT 'Error Message for the Signal if it is out of range --> Hardcoded and should have import export option from GUI',
    SEVERITY                VARCHAR (255) COMMENT 'Severity of the Signal like NONE,CRITICAL, IGNORE, etc --> Hardcoded and should have import export option from GUI',
    COMPARISON_ENABLE       TINYINT DEFAULT 1 COMMENT 'Comparison is 1 comparsion enable and 0 Comparison disable',
    MODE1_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE1_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE1_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE2_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE2_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE2_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE3_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE3_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE3_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE4_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE4_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE4_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE5_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE5_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE5_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
	MODE6_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE6_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE6_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE7_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE7_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE7_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE8_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE8_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE8_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE9_NOMINAL           VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE9_MIN              	VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE9_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE10_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE10_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE10_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE11_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE11_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE11_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE12_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE12_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE12_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE13_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE13_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE13_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE14_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE14_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE14_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE15_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE15_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE15_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE16_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE16_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE16_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI',
    MODE17_NOMINAL          VARCHAR (255) COMMENT 'Nominal Value for the mode, applicable for EQT(== +/-), EQ(==) and NE (!=)  --> Hardcoded and should have import export option from GUI',
    MODE17_MIN              VARCHAR (255) COMMENT 'Min Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value  --> Hardcoded and should have import export option from GUI',
    MODE17_MAX             	VARCHAR (255) COMMENT 'Max Limit for the mode, For GELE(>= <=) this is absolute value, For EQT(== +/-) This is Percentage of Nominal Value --> Hardcoded and should have import export option from GUI'
   
) COMMENT 'This table will store the LIMIT data for FE/FF Frames';