# Created by Abhay Kumar(uiv14167)
#Version 1.0
#Last Updated: 14/11/2024
# Added new coloum in FE Frame for 12V&48V Power Suppy in current and Voltage coloums.
# Added System Table for error log.
# Added Temperature table
# Added Updated the Datatype Signal data.
# 27Aug2024
# UUT INFO Table Added TEST_SEQUENCE column
#29Aug2024
# Added to Temperature Log and Power Status Log added Coloumn in Smae for Cycle Number and Test Mode
#02SEP2024
# Added Cycle duration tables
#09SEP2024
# Added to Temperature Relay Trip Feedback 
#30Sep2024
# Added to CAN Frame RX Byte length added in table FA,FF,FE
#05Nov2024
# Added socket info to Error log and test result log tables.
#14Nov2024
#deleted CAN_FRAME_RX_NO_OFF_BYTE fro UUT Info Table.
#03Jan2025
#Added Error Table added coloumn for Unit


-- -----------------------------------------------------
#CREATE SCHEMA <ProductName>+<ProductVariant>+<TestPhase>+<TestName>+<TimeStamp>;
#SQL for Copy a table from one schema to another;
#CREATE TABLE <ProductName>+<ProductVariant>+<TestPhase>+<TestName>+<TimeStamp>.PRODUCT_TEST_NAMES LIKE LTT_RESULTS_RESULTS.PRODUCT_TEST_NAMES;
#SQL for Copy data of table from one schema to another;
#INSERT INTO  <ProductName>+<ProductVariant>+<TestPhase>+<TestName>+<TimeStamp>.PRODUCT_TEST_NAMES SELECT * FROM LTT_RESULTS_RESULTS.PRODUCT_TEST_NAMES WHERE PRODUCT_TEST_NAMES.Test_Name = 'VIBRATION TEST';
-- -----------------------------------------------------
/*# Query to Create Sachema and Clone Table from existing schema to new schema
DROP SCHEMA IF EXISTS LTT_RESULT_OUTPUT_TABLES_TEST ;
CREATE SCHEMA LTT_RESULT_OUTPUT_TABLES_TEST;
CREATE TABLE LTT_RESULT_OUTPUT_TABLES_TEST.UUT_TEST_INFO LIKE LTT_RESULT_OUTPUT_TABLES.UUT_TEST_INFO;
*/

-- -----------------------------------------------------
-- SQL commands to create the Schema(database) in an MySQL.
-- Note that the schema name mentiond below is just a example, in actual it will be like below
-- <ProductName>+<ProductVariant>+<TestPhase>+<TestName>+<TimeStamp>
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Drop Schema ltt_result_output_tables if already exists and create new 
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS LTT_RESULT_OUTPUT_TABLES ;

CREATE SCHEMA IF NOT EXISTS LTT_RESULT_OUTPUT_TABLES ;

-- -----------------------------------------------------
-- Use  `ltt_result_output_tables`
-- -----------------------------------------------------

#USE LTT_RESULT_OUTPUT_TABLES ;

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`poduct_test_names`
-- -----------------------------------------------------

CREATE TABLE LTT_RESULT_OUTPUT_TABLES.PRODUCT_TEST_NAMES
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
    PRODUCT_NAME            VARCHAR (255) NOT NULL COMMENT 'Product Name i.e. eDCU_48V, eDCU_96V --> Hardcoded and should have import export option from GUI',
    TEST_NAME               VARCHAR (255) NOT NULL COMMENT 'Test Name like VIBRATION TEST, THERMAL ENDURANCE TEST -> Hardcoded and should have import export option from GUI',
    MISSION_PROFILE         VARCHAR (255) COMMENT 'Test Name like MISSION PROFILE 1, MISSION PROFILE 2 SHORT -> Hardcoded and should have import export option from GUI',
    CYCLE_DURATION	        INT COMMENT 'Test Duration of one cycle in seconds -> Hardcoded and should have import export option from GUI',
	NUMBER_OF_CYCLES        INT COMMENT 'Number of Test cycle needed to run -> Hardcoded and should have import export option from GUI',
    TOTAL_DURATION          INT	COMMENT 'Total Test Duration of one cycle in seconds -> Hardcoded and should have import export option from GUI'
) COMMENT 'This table will contain the Test related information for the products';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`uut_test_info`
-- -----------------------------------------------------

CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.UUT_TEST_INFO
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
    STATION_ID              VARCHAR (255) COMMENT 'Station ID in which ECU is getting tested ex. PC_NAME -->from TestSTand',
    TEST_SOCKET_INDEX       INT COMMENT 'Test socket in which ECU is getting tested ex. 0 to 5 -->from TestSTand',
    UUT_SERIAL_NUMBER       VARCHAR (255) COMMENT 'ECU Serial Number -->By Barcode or over CAN',
    TSW_VER					VARCHAR (255) COMMENT 'ECU Serial Number --> From Teststand over CAN',
    VAL_SW_VER				VARCHAR (255) COMMENT 'ECU Serial Number -->From Teststand over CAN',
    PROJECT_NAME            VARCHAR (255) COMMENT 'Project Name --> GUI -Normal String Control',
    PRODUCT_NAME            VARCHAR (255) COMMENT 'Product Name i.e. eDCU_48V, eDCU_96V --> GUI - Non-editable combo box',
    PRODUCT_VARIANT         VARCHAR (255) COMMENT 'Product Variant like eDCU_48V_CustomerName -> GUI - Non-editable combo box',
    TEST_NAME               VARCHAR (255) COMMENT 'Test Name like VIBRATION TEST, THERMAL ENDURANCE TEST -> GUI - Non-editable combo box',
    TEST_PHASE              VARCHAR (255) COMMENT 'DV/PV etc  --> GUI -Normal String Control',
    TEST_DESCRIPTION        VARCHAR (255) COMMENT 'Any other description about the test --> GUI -Normal String Control',
    TEMP_CHAMBER_NAME       VARCHAR (255) COMMENT 'Temperature Chamber Name -> GUI -Normal String Control',
    START_DATE_TIME         DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp of start of the test -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
    STOP_DATE_TIME          DATETIME(3) COMMENT 'Timestamp of stop of the test -->Using NOW(3) cmd',
    EXECUTION_TIME          DOUBLE COMMENT 'Test execution time in seconds -->from LabVIEW/TestSTand',
    START_CYCLE_COUNT		INT COMMENT 'Start of  Cycles Completed -->from LabVIEW/TestSTand', #NEW
    STOP_CYCLE_COUNT		INT COMMENT 'Cycle count on stop -->from LabVIEW/TestSTand', #NEW
    UUT_STATUS              VARCHAR (32) COMMENT 'Test Status ex Pass/Fail/Terminated/Error -->from LabVIEW/TestSTand',
    UUT_ERROR_CODE          INT COMMENT 'Error code in case of any error -->from LabVIEW/TestSTand',
    UUT_ERROR_MESSAGE       VARCHAR (1023) COMMENT 'Error Description in case of any error -->from LabVIEW/TestSTand',
    TEST_SEQUENCE           VARCHAR (1023) COMMENT 'Error Description in case of any error -->from LabVIEW/TestSTand'
) COMMENT 'This table will store the data generic infornation related UUT Test';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`fe_frame_log`
-- -----------------------------------------------------
 
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.FE_FRAME_LOG
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	UUT_TEST_INFO           INT NOT NULL COMMENT 'ID from UUT_TEST_INFO table for that perticular test --> MySQL DB',
    DATE_TIME               DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp when the Frame is received -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
    SOCKET_NUMBER           INT COMMENT 'Scoket Number of  Teststand -->from LabVIEW/TestSTand',
    CYCLE_NUMBER            INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
    TEST_MODE               VARCHAR (255) COMMENT 'Current Test Mode of Mission Profile -->from LabVIEW/TestSTand',
    CHAMBER_TEMP            DOUBLE COMMENT 'Current Temperature of Chamber -->from LabVIEW/TestSTand',
    LV_PPS_VOLTAGE           DOUBLE COMMENT 'Low Power Supply in Volttage -->from LabVIEW/TestSTand',
    LV_PPS_CURRENT           DOUBLE COMMENT 'Low Power Supply in Current -->from LabVIEW/TestSTand',
    HV_PPS_VOLTAGE           DOUBLE COMMENT 'High Power Supply in Volttage -->from LabVIEW/TestSTand',
    HV_PPS_CURRENT           DOUBLE COMMENT 'High Power Supply in Current -->from LabVIEW/TestSTand',
    CAN_FRAME_RX             VARCHAR (4096) COMMENT 'Raw CAN Frame received over STP -->from LabVIEW/TestSTand',
    CAN_FRAME_RX_NO_OFF_BYTE INT COMMENT 'Raw CAN Frame received no of byte over STP -->from LabVIEW/TestSTand',
   CONSTRAINT UUT_TEST_INFO_FE_FK FOREIGN KEY (UUT_TEST_INFO) REFERENCES UUT_TEST_INFO (ID)
) COMMENT 'This table will store the data for FE Frame';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`ff_frame_log`
-- -----------------------------------------------------

CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.FF_FRAME_LOG
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	UUT_TEST_INFO           INT NOT NULL COMMENT 'ID from UUT_TEST_INFO table for that perticular test --> MySQL DB',
    DATE_TIME               DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp when the Frame is received -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
    SOCKET_NUMBER           INT COMMENT 'Scoket Number of  Teststand -->from LabVIEW/TestSTand',
    CYCLE_NUMBER            INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
    TEST_MODE               VARCHAR (255) COMMENT 'Current Test Mode of Mission Profile -->from LabVIEW/TestSTand',
    CHAMBER_TEMP            DOUBLE COMMENT 'Current Temperature of Chamber -->from LabVIEW/TestSTand',
    CAN_FRAME_RX            VARCHAR (4096) COMMENT 'Raw CAN Frame received over STP -->from LabVIEW/TestSTand',
    CAN_FRAME_RX_NO_OFF_BYTE INT COMMENT 'Raw CAN Frame received no of byte over STP -->from LabVIEW/TestSTand',
    CONSTRAINT UUT_TEST_INFO_FF_FK FOREIGN KEY (UUT_TEST_INFO) REFERENCES UUT_TEST_INFO (ID)
) COMMENT 'This table will store the data for FF Frame';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`limit_table`
-- Insert Data from Input Limit table to Output Limit table
-- -----------------------------------------------------

CREATE TABLE LTT_RESULT_OUTPUT_TABLES.LIMIT_TABLE LIKE LTT_RESULT_INPUT_TABLES.LIMIT_TABLE;
#INSERT INTO  LTT_RESULT_OUTPUT_TABLES.LIMIT_TABLE SELECT * FROM LTT_RESULT_INPUT_TABLES.LIMIT_TABLE WHERE LIMIT_TABLE.TEST_NAME = 'VIBRATION TEST';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`error_log`
-- -----------------------------------------------------
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.ERROR_LOG
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	UUT_TEST_INFO           INT NOT NULL COMMENT 'ID from UUT_TEST_INFO table for that perticular test --> MySQL DB',
    LIMITID                 INT NOT NULL COMMENT 'ID from LIMIT_TABLE table for that perticular failure --> MySQL DB',
    FRAME_TYPE 				VARCHAR (255) COMMENT 'Type of frame FE or FF -->from LabVIEW/TestSTand',
    DATE_TIME               DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp when the Frame is received -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
    SOCKET_NUMBER           INT COMMENT 'Scoket Number of  Teststand -->from LabVIEW/TestSTand',
    CYCLE_NUMBER            INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
    TEST_MODE               VARCHAR (255) COMMENT 'Current Test Mode of Mission Profile -->from LabVIEW/TestSTand',
    SIGNAL_NAME          	VARCHAR (255) COMMENT 'Name of the Signal which is out of limit -->from LabVIEW/TestSTand',
    SIGNAL_VALUE            VARCHAR (255) COMMENT 'Signal values -->from LabVIEW/TestSTand',
    UNIT                    VARCHAR (255) COMMENT 'Signal Unit -->from LabVIEW/TestSTand',
    COMPARISON_VALUE        VARCHAR (255) COMMENT ' Example Comparison Message Frame 10<=x<=20--> from LabVIEW/TestSTand',
    ERROR_MESSAGE           VARCHAR (255) COMMENT ' Error Message Like Error Text: Signal,Actual Value, Type of ERROR :  (Min Value Limit/ Max Values Limit) -which is crossed --> from LabVIEW/TestSTand',
    CONSTRAINT LIMITID_FK FOREIGN KEY (LIMITID) REFERENCES LIMIT_TABLE (ID),
    CONSTRAINT UUT_TEST_INFO_ERROR_LOG_FK FOREIGN KEY (UUT_TEST_INFO) REFERENCES UUT_TEST_INFO (ID)
) COMMENT 'This table will store the failures for FE/FF Frames wrt cycle and modes';
-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`test_result_log`
-- -----------------------------------------------------
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.TEST_RESULT_LOG
(
    ID                      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	UUT_TEST_INFO           INT NOT NULL COMMENT 'ID from UUT_TEST_INFO table for that perticular test --> MySQL DB',
    LIMITID                 INT NOT NULL COMMENT 'ID from LIMIT_TABLE table for that perticular failure --> MySQL DB',
    FRAME_TYPE 				VARCHAR (255) COMMENT 'Type of frame FE or FF -->from LabVIEW/TestSTand',
    DATE_TIME               DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp when the Frame is received -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
    SOCKET_NUMBER           INT COMMENT 'Scoket Number of  Teststand -->from LabVIEW/TestSTand',
    CYCLE_NUMBER            INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
    TEST_MODE               VARCHAR (255) COMMENT 'Current Test Mode of Mission Profile -->from LabVIEW/TestSTand',
    SIGNAL_NAME          	VARCHAR (255) COMMENT 'Name of the Signal which is out of limit -->from LabVIEW/TestSTand',
    SIGNAL_VALUE            DOUBLE COMMENT 'Signal values -->from LabVIEW/TestSTand',
    COMPARISON_VALUE        VARCHAR (255) COMMENT ' Example Comparison Message Frame 10<=x<=20--> from LabVIEW/TestSTand',
    TEST_RESULT             VARCHAR (255) COMMENT ' Example Pass/Fail--> from LabVIEW/TestSTand',
    ERROR_MESSAGE           VARCHAR (255) COMMENT ' Error Message Like Error Text: Signal,Actual Value, Type of ERROR :  (Min Value Limit/ Max Values Limit) -which is crossed --> from LabVIEW/TestSTand',
    CONSTRAINT LIMITID_RESULT_FK FOREIGN KEY (LIMITID) REFERENCES LIMIT_TABLE (ID),
    CONSTRAINT UUT_TEST_INFO_RESULT_LOG_FK FOREIGN KEY (UUT_TEST_INFO) REFERENCES UUT_TEST_INFO (ID)
) COMMENT 'This table will store the failures for FE/FF Frames wrt cycle and modes';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`system_error_log`
-- -----------------------------------------------------
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.SYSTEM_ERROR_LOG
(
    ID                 INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	DATE_TIME          DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp when the Frame is received -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
    CYCLE_NUMBER       INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
	TEST_MODE          VARCHAR (255) COMMENT ' Current Test Mode --> from LabVIEW/TestSTand',
    ERROR_MESSAGE      VARCHAR (4096) COMMENT 'Error Message / Full Details for Description ---> from LabVIEW/TestSTand'
    ) COMMENT 'This table will store the System failures';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`temperature_log`
-- -----------------------------------------------------
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.TEMPERATURE_LOG
(
    ID                 INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	DATE_TIME          DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp when the Frame is received -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
    CYCLE_NUMBER       INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
	TEST_MODE          VARCHAR (255) COMMENT ' Current Test Mode --> from LabVIEW/TestSTand',
    LV_PPS_TEMPERATURE       DOUBLE COMMENT 'Lower Power Supply Tempearature live reading -->from LabVIEW/TestSTand',
    HV_PPS1_TEMPERATURE      DOUBLE COMMENT 'High Power Supply 1 Tempearature live reading -->from LabVIEW/TestSTand',
	HV_PPS2_TEMPERATURE      DOUBLE COMMENT 'High Power Supply 2 Tempearature live reading -->from LabVIEW/TestSTand',
    HV_PPS3_TEMPERATURE      DOUBLE COMMENT 'High Power Supply 3 Tempearature live reading -->from LabVIEW/TestSTand',
    HV_PPS4_TEMPERATURE      DOUBLE COMMENT 'High Power Supply 4 Tempearature live reading -->from LabVIEW/TestSTand',
    HV_PPS5_TEMPERATURE      DOUBLE COMMENT 'High Power Supply 5 Tempearature live reading -->from LabVIEW/TestSTand',
    HV_PPS6_TEMPERATURE      DOUBLE COMMENT 'High  Power Supply 6 Tempearature live reading -->from LabVIEW/TestSTand',
    CHAMBER_TEMPERATURE      DOUBLE COMMENT 'Chamber Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_U1_TEMPERATURE      DOUBLE COMMENT 'Load U Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_V1_TEMPERATURE      DOUBLE COMMENT 'Load U Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_W1_TEMPERATURE      DOUBLE COMMENT 'Load U Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_U2_TEMPERATURE      DOUBLE COMMENT 'Load V Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_V2_TEMPERATURE      DOUBLE COMMENT 'Load U Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_W2_TEMPERATURE      DOUBLE COMMENT 'Load U Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_U3_TEMPERATURE      DOUBLE COMMENT 'Load U Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_V3_TEMPERATURE      DOUBLE COMMENT 'Load U Tempearature live reading -->from LabVIEW/TestSTand',
    LOAD_W3_TEMPERATURE      DOUBLE COMMENT 'Load W Tempearature live reading -->from LabVIEW/TestSTand',
    LV_PPS_TEMPERATURE_RELAY_FB      VARCHAR (45) COMMENT 'Lower Power Supply Tempearature relay feedback reading -->from LabVIEW/TestSTand',
    HV_PPS1_TEMPERATURE_RELAY_FB     VARCHAR (45) COMMENT 'High Power Supply relay feedback reading -->from LabVIEW/TestSTand',
	HV_PPS2_TEMPERATURE_RELAY_FB     VARCHAR (45) COMMENT 'High Power Supply relay feedback reading -->from LabVIEW/TestSTand',
    HV_PPS3_TEMPERATURE_RELAY_FB     VARCHAR (45) COMMENT 'High Power Supply relay feedback reading  -->from LabVIEW/TestSTand',
    HV_PPS4_TEMPERATURE_RELAY_FB     VARCHAR (45) COMMENT 'High Power Supply relay feedback reading -->from LabVIEW/TestSTand',
    HV_PPS5_TEMPERATURE_RELAY_FB     VARCHAR (45) COMMENT 'High Power Supply relay feedback reading -->from LabVIEW/TestSTand',
    HV_PPS6_TEMPERATURE_RELAY_FB     VARCHAR (45) COMMENT 'High  Power Supply relay feedback reading -->from LabVIEW/TestSTand',
    CHAMBER_TEMPERATURE_RELAY_FB     VARCHAR (45) COMMENT 'Chamber Tempearature relay feedback reading -->from LabVIEW/TestSTand'
    ) COMMENT 'This table will store the System failures';

-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`power_status_log`
-- -----------------------------------------------------
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.POWER_STATUS_LOG
(
    ID                 INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	DATE_TIME          DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Timestamp when the Frame is received -->Using DEFAULT CURRENT_TIMESTAMP(3) inserted Automaticly',
	CYCLE_NUMBER       INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
	TEST_MODE          VARCHAR (255) COMMENT ' Current Test Mode --> from LabVIEW/TestSTand',
    TYPE_POWER         VARCHAR (255) COMMENT ' Power trip types --> from LabVIEW/TestSTand',
    STATE              VARCHAR (255) COMMENT 'State Details for ON/OFF ---> from LabVIEW/TestSTand'
    ) COMMENT 'This table will store the Power failures logs';
-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`cycle_off_duration_log`
-- -----------------------------------------------------
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.CYCLE_OFF_DURATION_LOG
(
    ID                   INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	CYCLE_NUMBER         INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
	eDCU_OFF_START_TIME  DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Duration of the eDCU OFF_START Time ---> from LabVIEW/TestSTand',
    eDCU_OFF_STOP_TIME   DATETIME(3)  COMMENT'Duration of the eDCU OFF_STOP Time ---> from LabVIEW/TestSTand',
    eDCU_OFF_DURATION    DOUBLE COMMENT 'Duration of the eDCU OFF_DURATION Time ---> from LabVIEW/TestSTand'
    ) COMMENT 'This table will store the test off duration logs';
    
-- -----------------------------------------------------
-- Table `ltt_result_output_tables`.`cycle_on_duration_log`
-- -----------------------------------------------------
CREATE TABLE  LTT_RESULT_OUTPUT_TABLES.CYCLE_ON_DURATION_LOG
(
    ID                   INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique ID for the Table -->generated by  default',
	CYCLE_NUMBER         INT COMMENT 'Current Test Cycle Number of Mission Profile -->from LabVIEW/TestSTand',
    eDCU_ON_START_TIME   DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Duration of the eDCU ON_START Time ---> from LabVIEW/TestSTand',
    eDCU_ON_STOP_TIME    DATETIME(3)  COMMENT'Duration of the eDCU ON_STOP Time ---> from LabVIEW/TestSTand',
    eDCU_ON_DURATION     DOUBLE COMMENT 'Duration of the eDCU ON_DURATION Time ---> from LabVIEW/TestSTand'
    ) COMMENT 'This table will store the test on duration logs';    
    
-- -----------------------------------------------------
-- Views `ltt_result_output_tables`.`test overview`
-- -----------------------------------------------------   
CREATE VIEW `ltt_result_output_tables`.`test overview` AS 
(    SELECT 
        `ltt_result_output_tables`.`uut_test_info`.`STATION_ID` AS `STATION_ID`,
        `ltt_result_output_tables`.`uut_test_info`.`TEST_SOCKET_INDEX` AS `TEST_SOCKET_INDEX`,
        `ltt_result_output_tables`.`uut_test_info`.`UUT_SERIAL_NUMBER` AS `UUT_SERIAL_NUMBER`,
        `ltt_result_output_tables`.`uut_test_info`.`PROJECT_NAME` AS `PROJECT_NAME`,
        `ltt_result_output_tables`.`uut_test_info`.`PRODUCT_NAME` AS `PRODUCT_NAME`,
        `ltt_result_output_tables`.`uut_test_info`.`PRODUCT_VARIANT` AS `PRODUCT_VARIANT`,
        `ltt_result_output_tables`.`uut_test_info`.`TEST_NAME` AS `TEST_NAME`,
        `ltt_result_output_tables`.`uut_test_info`.`TEST_PHASE` AS `TEST_PHASE`,
        `ltt_result_output_tables`.`uut_test_info`.`TEST_DESCRIPTION` AS `TEST_DESCRIPTION`,
        `ltt_result_output_tables`.`uut_test_info`.`TEMP_CHAMBER_NAME` AS `TEMP_CHAMBER_NAME`,
        `ltt_result_output_tables`.`uut_test_info`.`START_DATE_TIME` AS `START_DATE_TIME`,
        `ltt_result_output_tables`.`uut_test_info`.`STOP_DATE_TIME` AS `STOP_DATE_TIME`,
        `ltt_result_output_tables`.`uut_test_info`.`UUT_STATUS` AS `UUT_STATUS`,
        `ltt_result_output_tables`.`uut_test_info`.`UUT_ERROR_CODE` AS `UUT_ERROR_CODE`,
        `ltt_result_output_tables`.`uut_test_info`.`UUT_ERROR_MESSAGE` AS `UUT_ERROR_MESSAGE`,
        `ltt_result_output_tables`.`product_test_names`.`MISSION_PROFILE` AS `MISSION_PROFILE`,
        `ltt_result_output_tables`.`product_test_names`.`NUMBER_OF_CYCLES` AS `NUMBER_OF_CYCLES`,
		`ltt_result_output_tables`.`product_test_names`.`CYCLE_DURATION` AS `CYCLE_DURATION`,
        `ltt_result_output_tables`.`product_test_names`.`TOTAL_DURATION` AS `TOTAL_DURATION`,
        `ltt_result_output_tables`.`uut_test_info`.`STOP_CYCLE_COUNT` AS `CYCLES_COMPLETED`,
        `product_test_names`.`NUMBER_OF_CYCLES` - `uut_test_info`.`STOP_CYCLE_COUNT` AS 'REMAINING_CYCLES',
        (`product_test_names`.`NUMBER_OF_CYCLES` - `uut_test_info`.`STOP_CYCLE_COUNT`) * `product_test_names`.`CYCLE_DURATION` AS 'REMAINING_DURATION'
    FROM
        (`ltt_result_output_tables`.`uut_test_info`
        JOIN `ltt_result_output_tables`.`product_test_names` ON (((`ltt_result_output_tables`.`uut_test_info`.`PRODUCT_NAME` = `ltt_result_output_tables`.`product_test_names`.`PRODUCT_NAME`)
            AND (`ltt_result_output_tables`.`uut_test_info`.`TEST_NAME` = `ltt_result_output_tables`.`product_test_names`.`TEST_NAME`))))
 )   
